name: Release Go project

on:
  push:
    tags:
      - "v1.*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/


      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist --config /home/runner/work/schoolantwoorden-cli/schoolantwoorden-cli/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
